parameters:
    user.profile_img_placeholder: 'profileimg-placeholder.jpg'

services:
    user.user:
        class: BackendBundle\Services\UserServices
        arguments: [ "@doctrine.orm.entity_manager", "@app.helpers", "@app.jwt_auth", "%user.profile_img_placeholder%" ]

    usergroup.usergroup:
        class: BackendBundle\Services\UsergroupServices
        arguments: [ "@doctrine.orm.entity_manager", "@app.helpers", "@app.jwt_auth" ]
